import SideNav from "@/components/molecules/sideNav/SideNav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sample App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="text-black flex h-screen flex-col md:flex-row">
          <div className="w-full flex-none md:w-64">
            <SideNav />
          </div>
          <main>
            <div className="p-6 md:p-12">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
