"use client";

import SideNav from "@/components/molecules/SideNav/SideNav";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Sample App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col text-black md:flex-row md:overflow-hidden">
          {/* <div className="w-full flex-none md:w-64"> */}
          <div
            className={cn("flex w-[250px]", {
              hidden: pathname == "/login" || pathname == "/signup",
            })}
          >
            <SideNav />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}
          </div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
